differential_1st=function(func,step=0.00001){
	return(function(x,...){return((func(x+step/2,...)-func(x-step/2,...))/step)})
}
differential_2nd=function(func,step=0.00001){
	return(function(x,y,...){return((func(x,y+step/2,...)-func(x,y-step/2,...))/step)})
}
differential_3rd=function(func,step=0.00001){
	return(function(x,y,z,...){return((func(x,y,z+step/2,...)-func(x,y,z-step/2,...))/step)})
}
differential_4th=function(func,step=0.00001){
	return(function(x,y,z,w,...){return((func(x,y,z,w+step/2,...)-func(x,y,z,w-step/2,...))/step)})
}
differential=function(func,step=0.00001){
	return(function(x){return((func(x+step/2)-func(x-step/2))/step)})
}
second_differential_1st=function(func,step=0.00001){
	return(function(x,...){return(2/step*((2*func(x+step/2,...)+2*func(x-step/2,...)-4*func(x,...))/step))})
}
second_differential_2nd=function(func,step=0.00001){
	return(function(x,y,...){return(2/step*((2*func(x,y+step/2,...)+2*func(x,y-step/2,...)-4*func(x,y,...))/step))})
}
second_differential_3rd=function(func,step=0.00001){
	return(function(x,y,z,...){return(2/step*((2*func(x,y,z+step/2,...)+2*func(x,y,z-step/2,...)-4*func(x,y,z,...))/step))})
}
second_differential_4th=function(func,step=0.00001){
	return(function(x,y,z,w,...){return(2/step*((2*func(x,y,z,w+step/2,...)+2*func(x,y,z,w-step/2,...)-4*func(x,y,z,w,...))/step))})
}
differential_1st = differential
second_differential = second_differential_1st
